trigger: none   # no push triggers

pr:
  branches:
    include:
      - staging

pool:
  CI # pipeline always runs on this pool

variables:
  CI_COMMIT_SHORT_SHA: $(Build.BuildId)
  BUILD_DIR: $(Build.SourcesDirectory)
  COMPOSE_FILE: .docker/docker-compose.ci.yml
stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: build_container
        steps:
          - script: |
              docker compose build keycloak-users-synchronizer
              docker compose -p $(APP_NAME)_$(CI_COMMIT_SHORT_SHA) up -d
            displayName: build
  - stage: Security
    displayName: Security
    jobs:
      - template: templates/start_container.yml
      - template: templates/security/check_gemfile_job.yml
      - template: templates/security/bundle_audit_job.yml
      - job: clean_up
        displayName: CleanUp
        condition: and(always(), gt(variables['System.StageAttempt'], 1))
        dependsOn:
          - check_gemfile
          - bundle_audit
        steps:
        - template: templates/clean_up/clean_up_job.yml          
  - stage: CleanUp
    condition: always()
    displayName: Clean Up
    jobs:
     - job: clean_up
       displayName: CleanUp
       continueOnError: true
       steps:
       - template: templates/clean_up/clean_up_job.yml
