jobs:
  - job: generate_env_file
    displayName: Generate .env File
    continueOnError: true
    steps:
      - script: |
          cat > .env << EOF
          KEYCLOAK_BASE_URL=$(KEYCLOAK_BASE_URL)
          KEYCLOAK_CLIENT_ID=$(KEYCLOAK_CLIENT_ID)
          KEYCLOAK_CLIENT_SECRET=$(KEYCLOAK_CLIENT_SECRET)
          KEYCLOAK_REALM=$(KEYCLOAK_REALM)
          KEYCLOAK_ADMIN_USERNAME=$(KEYCLOAK_ADMIN_USERNAME)
          KEYCLOAK_ADMIN_PASSWORD=$(KEYCLOAK_ADMIN_PASSWORD)
          KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME=$(KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME)
          KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD=$(KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD)
          KAFKA_BOOTSTRAP_SERVERS=$(KAFKA_BOOTSTRAP_SERVERS)
          KAFKA_CLIENT_ID=$(KAFKA_CLIENT_ID)
          KARAFKA_ENV=$(KARAFKA_ENV)
          EOF
        displayName: Generate .env file
        env:
          SECRET_KEY: $(SECRET_KEY)  # explicitly map secrets