jobs:
- job: bundle_audit
  displayName: Bundle Audit
  dependsOn: start_containers
  continueOnError: true
  steps:
    - script: |
        docker compose -p $(APP_NAME)_$(CI_COMMIT_SHORT_SHA) exec keycloak-users-synchronizer bundle exec bundle-audit check --update
      displayName: Bundle Audit
