jobs:
- job: rubocop
  displayName: Rubocop
  dependsOn: start_containers
  continueOnError: true
  steps:
    - script: |
        docker compose -p $(APP_NAME)_$(CI_COMMIT_SHORT_SHA) exec keycloak-users-synchronizer bundle exec rubocop --format progress --format json -o .rubocop/rubocop.json
      displayName: 'rubocop'
      continueOnError: true
    - script: |
        CONTAINER_ID=$(APP_NAME)_$(CI_COMMIT_SHORT_SHA)
        mkdir -p $(Build.SourcesDirectory)/Rubocop_Report
        docker cp "$CONTAINER_ID:/app/.rubocop" $(Build.SourcesDirectory)/Rubocop_Report/.rubocop
      displayName: 'Copy Coverage Reports and Clean Up'
    - publish: $(Build.SourcesDirectory)/Rubocop_Report
      artifact: Rubocop_Report
      displayName: 'Publish Coverage Report'
      condition: always()
