  keycloak-users-synchronizer:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      args: # Goes to dockerfile ARGS (needs to have $ARG to catch this value)
        - APP_USER_GID=1010 # group should be created in host with: sudo groupadd -g 1010 app_group
        - APP_USER_UID=1011 # user should be created in host with: sudo useradd -r -u 1011 -g app_group app_user
    image: registryqa.aquaporservicos.pt:5000/keycloak_users_synchronizer_qa:latest
    command: bin/start
    environment: # Goes directly to ENV inside container (cachtes env from azure ci)
      TZ: Europe/Lisbon
      DOCKER: true
      KEYCLOAK_BASE_URL: ${KEYCLOAK_BASE_URL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME}
      KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_CLIENT_ID: ${KAFKA_CLIENT_ID}
      KARAFKA_ENV: ${KARAFKA_ENV}
    networks:
      kafka_network:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        max_replicas_per_node: 1
          constraints:
            - "node.role == manager"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 1
      resources:
        limits:
          cpus: '2'
          memory: 500m