  keycloak-users-synchronizer:
    args: # Goes to dockerfile ARGS (needs to have $ARG to catch this value)
      - APP_USER_GID=1010 # group should be created in host with: sudo groupadd -g 1010 app_group
      - APP_USER_UID=1011 # user should be created in host with: sudo useradd -r -u 1011 -g app_group app_user
    image: registry.aquaporservicos.pt:5000/keycloak_users_synchronizer:latest
    command: bin/start
    environment:
      - TZ=Europe/Lisbon
      - DOCKER=true
    networks:
      kafka_network:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      placement:
       max_replicas_per_node: 1
        constraints:
          - "node.role == manager"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 1
      resources:
        limits:
          cpus: '2'
          memory: 500m